#!/usr/bin/env bash
# Generate Alertmanager config with optional Slack + Email from .env
# Usage: bash scripts/configure-alerts.sh && docker compose restart alertmanager

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT="$ROOT/alertmanager/alertmanager.yml"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing .env — copy .env.example to .env first"
  exit 1
fi

# shellcheck disable=SC1090
set -a
# Read KEY=VAL lines
while IFS= read -r line || [[ -n "$line" ]]; do
  [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
  if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
    export "${BASH_REMATCH[1]}=${BASH_REMATCH[2]}"
  fi
done < "$ENV_FILE"
set +a

SLACK_URL="${SLACK_WEBHOOK_URL:-}"
SLACK_CHANNEL="${SLACK_CHANNEL:-#alerts}"
SMTP_HOST="${SMTP_SMARTHOST:-}"
SMTP_FROM="${SMTP_FROM:-}"
SMTP_USER="${SMTP_USERNAME:-}"
SMTP_PASS="${SMTP_PASSWORD:-}"
ALERT_TO="${ALERT_EMAIL_TO:-}"

GLOBAL_SMTP=""
if [[ -n "$SMTP_HOST" && -n "$SMTP_FROM" ]]; then
  GLOBAL_SMTP=$(cat <<EOF
  smtp_smarthost: '${SMTP_HOST}'
  smtp_from: '${SMTP_FROM}'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASS}'
  smtp_require_tls: true
EOF
)
  echo "Email SMTP configured: $SMTP_HOST -> $ALERT_TO"
else
  echo "Email not configured (SMTP_SMARTHOST / SMTP_FROM empty)"
fi

if [[ -n "$SLACK_URL" ]]; then
  echo "Slack webhook configured -> $SLACK_CHANNEL"
else
  echo "Slack not configured (SLACK_WEBHOOK_URL empty)"
fi

receiver_block() {
  local name="$1"
  local slack=""
  local email=""
  if [[ -n "$SLACK_URL" ]]; then
    slack=$(cat <<EOF

    slack_configs:
      - api_url: '${SLACK_URL}'
        channel: '${SLACK_CHANNEL}'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
EOF
)
  fi
  if [[ -n "$SMTP_HOST" && -n "$ALERT_TO" ]]; then
    email=$(cat <<EOF

    email_configs:
      - to: '${ALERT_TO}'
        send_resolved: true
        headers:
          Subject: '{{ template "email.subject" . }}'
        html: '{{ template "email.html" . }}'
EOF
)
  fi
  cat <<EOF
  - name: ${name}
    webhook_configs:
      - url: "http://alert-logger:9999/webhook"
        send_resolved: true${slack}${email}
EOF
}

cat > "$OUT" <<EOF
# AUTO-GENERATED by scripts/configure-alerts.sh — do not edit by hand

global:
  resolve_timeout: 5m
${GLOBAL_SMTP}
templates:
  - /etc/alertmanager/templates/*.tmpl

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: [alertname, instance]

route:
  receiver: default-receiver
  group_by: [alertname, severity, team]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity="critical"
      receiver: critical-receiver
      continue: true
    - matchers:
        - team="application"
      receiver: app-team
    - matchers:
        - team="infrastructure"
      receiver: infra-team
    - matchers:
        - team="database"
      receiver: db-team

receivers:
$(receiver_block default-receiver)
$(receiver_block critical-receiver)
$(receiver_block app-team)
$(receiver_block infra-team)
$(receiver_block db-team)
EOF

echo "Wrote $OUT"
echo "Apply with: docker compose restart alertmanager"
