# Generate Alertmanager config with optional Slack + Email from .env
# Usage:  .\scripts\configure-alerts.ps1
# Then:   docker compose restart alertmanager

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root ".env"

if (-not (Test-Path $envFile)) {
    Write-Error "Missing .env — copy .env.example to .env first"
}

# Load .env
Get-Content $envFile | ForEach-Object {
    if ($_ -match '^\s*#' -or $_ -match '^\s*$') { return }
    $parts = $_ -split '=', 2
    if ($parts.Length -eq 2) {
        $name = $parts[0].Trim()
        $value = $parts[1].Trim().Trim('"').Trim("'")
        Set-Item -Path "Env:$name" -Value $value
    }
}

$slackUrl = $env:SLACK_WEBHOOK_URL
$slackChannel = if ($env:SLACK_CHANNEL) { $env:SLACK_CHANNEL } else { "#alerts" }
$smtpHost = $env:SMTP_SMARTHOST
$smtpFrom = $env:SMTP_FROM
$smtpUser = $env:SMTP_USERNAME
$smtpPass = $env:SMTP_PASSWORD
$alertTo = $env:ALERT_EMAIL_TO

$globalSmtp = ""
if ($smtpHost -and $smtpFrom) {
    $globalSmtp = @"
  smtp_smarthost: '$smtpHost'
  smtp_from: '$smtpFrom'
  smtp_auth_username: '$smtpUser'
  smtp_auth_password: '$smtpPass'
  smtp_require_tls: true
"@
    Write-Host "Email SMTP configured: $smtpHost -> $alertTo" -ForegroundColor Green
} else {
    Write-Host "Email not configured (SMTP_SMARTHOST / SMTP_FROM empty)" -ForegroundColor Yellow
}

function ReceiverBlock($name) {
    $slack = ""
    if ($slackUrl) {
        $slack = @"

    slack_configs:
      - api_url: '$slackUrl'
        channel: '$slackChannel'
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
"@
    }

    $email = ""
    if ($smtpHost -and $alertTo) {
        $email = @"

    email_configs:
      - to: '$alertTo'
        send_resolved: true
        headers:
          Subject: '{{ template "email.subject" . }}'
        html: '{{ template "email.html" . }}'
"@
    }

    return @"
  - name: $name
    webhook_configs:
      - url: "http://alert-logger:9999/webhook"
        send_resolved: true$slack$email
"@
}

if ($slackUrl) {
    Write-Host "Slack webhook configured -> $slackChannel" -ForegroundColor Green
} else {
    Write-Host "Slack not configured (SLACK_WEBHOOK_URL empty)" -ForegroundColor Yellow
}

$yml = @"
# AUTO-GENERATED by scripts/configure-alerts.ps1 — do not edit by hand
# Re-run that script after changing .env

global:
  resolve_timeout: 5m
$globalSmtp
templates:
  - /etc/alertmanager/templates/*.tmpl

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: [alertname, instance]

route:
  receiver: default-receiver
  group_by: [alertname, severity, team]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity="critical"
      receiver: critical-receiver
      continue: true
    - matchers:
        - team="application"
      receiver: app-team
    - matchers:
        - team="infrastructure"
      receiver: infra-team
    - matchers:
        - team="database"
      receiver: db-team

receivers:
$(ReceiverBlock 'default-receiver')
$(ReceiverBlock 'critical-receiver')
$(ReceiverBlock 'app-team')
$(ReceiverBlock 'infra-team')
$(ReceiverBlock 'db-team')
"@

$out = Join-Path $root "alertmanager\alertmanager.yml"
Set-Content -Path $out -Value $yml -Encoding UTF8
Write-Host "Wrote $out" -ForegroundColor Cyan
Write-Host "Apply with: docker compose restart alertmanager" -ForegroundColor Cyan
